package day0305;

public class Ex9Exception {

	public static void main(String[] args) {
		
		System.out.println("프로그램 시작");
		
		try { 
			//예외발생할 코드
		int num=5/0;  //정수를 0으로 나누면 에러 발생
		}catch(ArithmeticException e) {
			
		}
		
		System.out.println("프로그램 정상종료!!!");
	}

}
